# Generated by Django 3.1.1 on 2020-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60, unique=True)),
                ('is_a_gallery', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_file', models.ImageField(unique=True, upload_to='albums/images/')),
                ('appear_in_album', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='albums.Tag')),
            ],
        ),
    ]
