# Generated by Django 3.0.8 on 2020-08-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.BooleanField()),
                ('tag2', models.BooleanField()),
                ('tag3', models.BooleanField()),
                ('tag4', models.BooleanField()),
                ('tag5', models.BooleanField()),
                ('tag6', models.BooleanField()),
                ('tag7', models.BooleanField()),
                ('tag8', models.BooleanField()),
                ('tag9', models.BooleanField()),
                ('tag10', models.BooleanField()),
            ],
        ),
    ]
