# Generated by Django 3.0.8 on 2020-08-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagname',
            new_name='tagnam',
        ),
    ]
