# Generated by Django 3.1.1 on 2020-12-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='owner',
            new_name='user',
        ),
    ]
