# Generated by Django 3.1.1 on 2021-01-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20201214_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(max_length=50)),
                ('web_url', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='landing/logos/')),
                ('enable_about_me', models.BooleanField(default=True)),
                ('about_me', models.TextField()),
                ('enable_contact_me', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('enable_get_involved', models.BooleanField(default=True)),
                ('land_background', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
