# Generated by Django 3.1.1 on 2021-01-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210130_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='land_background',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image', verbose_name='homepage bakground'),
        ),
    ]
