# Generated by Django 3.1.1 on 2021-02-01 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210130_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='land_background',
            field=models.OneToOneField(blank=True, limit_choices_to={'user': models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image', verbose_name='homepage bakground'),
        ),
    ]
